# admin-web (Angular CSR) — статика за nginx
FROM node:22-alpine AS build
WORKDIR /workspace
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx build admin-web

FROM nginx:alpine AS runtime
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/dist/apps/admin-web/browser /usr/share/nginx/html
EXPOSE 80
