# main-web (Angular SSR) — рендер-сервис (Node)
FROM node:22-alpine AS build
WORKDIR /workspace
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx build main-web

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /workspace/dist/apps/main-web ./
COPY --from=build /workspace/node_modules ./node_modules
EXPOSE 4000
CMD ["node", "server/server.mjs"]
